spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/cragsupplyco
    username: postgres
    password: ${DB_PWD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
